/**
 * Anti Control Tower — 사이트 단일 소스 (Single Source of Truth)
 * API(health/alert)와 프론트엔드가 이 목록을 기준으로 동작한다.
 *
 * adsense: approved | pending | none
 * category: diagnosis | ministry | content | tools | ops
 * status: running | maintenance | archived (운영 의도 상태, 헬스와 별개)
 */

const SITES = [
  // ── 진단 레이더 (수익 메인 라인) ──────────────────────────
  {
    id: 'mz-radar',
    name: 'MZ 레이더',
    sub: 'MZ 직장인 유형 진단',
    category: 'diagnosis',
    status: 'running',
    adsense: 'approved',
    gsc: true,
    seoText: true,
    domain: 'mz-radar.vercel.app',
    github: 'CHOBH1024/mz-radar',
    icon: 'fa-rocket',
    color: '#4f8ef7',
    desc: '에니어그램 기반 MZ 직장 생존 DNA 진단',
  },
  {
    id: 'burnout-radar',
    name: '번아웃 레이더',
    sub: '번아웃 위험도 진단',
    category: 'diagnosis',
    status: 'running',
    adsense: 'pending',
    gsc: true,
    seoText: true,
    domain: 'burnout-radar.vercel.app',
    github: 'CHOBH1024/burnout-radar',
    icon: 'fa-fire-extinguisher',
    color: '#fb4570',
    desc: '직장인 소진 패턴·스트레스 진단',
  },
  {
    id: 'genius-radar',
    name: '지니어스 레이더',
    sub: '다중지능 진단',
    category: 'diagnosis',
    status: 'running',
    adsense: 'approved',
    gsc: true,
    seoText: true,
    domain: 'genius-radar.vercel.app',
    github: 'CHOBH1024/genius-radar',
    icon: 'fa-brain',
    color: '#9f6ef6',
    desc: '하워드 가드너 다중지능 기반 천재성 진단',
  },
  {
    id: 'fx-radar',
    name: 'FX 레이더',
    sub: '투자 편향 진단',
    category: 'diagnosis',
    status: 'running',
    adsense: 'approved',
    gsc: true,
    seoText: false,
    domain: 'fx-radar.vercel.app',
    github: 'CHOBH1024/fx-radar',
    icon: 'fa-arrow-trend-up',
    color: '#2dd4bf',
    desc: '행동재무학 기반 투자 편향 9종 진단',
  },
  {
    id: 'mood-weather',
    name: '무드 웨더',
    sub: '감정 날씨 일기',
    category: 'diagnosis',
    status: 'running',
    adsense: 'approved',
    gsc: true,
    seoText: false,
    domain: 'mood-weather.vercel.app',
    github: 'CHOBH1024/mood-weather',
    icon: 'fa-cloud-sun',
    color: '#fbbf24',
    desc: '오늘 감정 날씨 레이더 진단',
  },
  {
    id: 'money-radar',
    name: '머니 레이더',
    sub: '소비·재테크 성향',
    category: 'diagnosis',
    status: 'running',
    adsense: 'none',
    gsc: false,
    seoText: false,
    domain: 'money-radar.vercel.app',
    github: 'CHOBH1024/money-radar',
    icon: 'fa-coins',
    color: '#22c55e',
    desc: '행동경제학 기반 돈 DNA 진단',
  },
  {
    id: 'ilban-leadership',
    name: '일반 리더십',
    sub: '리더십 유형 진단',
    category: 'diagnosis',
    status: 'running',
    adsense: 'pending',
    gsc: true,
    seoText: true,
    domain: 'ilban-leadership.vercel.app',
    github: 'CHOBH1024/ilban-leadership',
    icon: 'fa-people-group',
    color: '#0ea5e9',
    desc: '카리스마·서번트·코칭 리더십 유형 진단',
  },
  {
    id: 'aikiugihimdulda',
    name: '아이키우기힘들다',
    sub: '육아 스타일 진단',
    category: 'diagnosis',
    status: 'running',
    adsense: 'pending',
    gsc: true,
    seoText: true,
    domain: 'aikiugihimdulda.vercel.app',
    github: 'CHOBH1024/aikiugihimdulda',
    icon: 'fa-baby',
    color: '#f472b6',
    desc: 'Mirror Inside Parenting 육아 페르소나 진단',
  },
  {
    id: 'mirrior-app',
    name: '미러 인사이트',
    sub: '진단 템플릿 본체',
    category: 'diagnosis',
    status: 'running',
    adsense: 'pending',
    gsc: true,
    seoText: true,
    domain: 'mirrior-app.vercel.app',
    github: 'CHOBH1024/MIRRIOR-APP',
    icon: 'fa-clone',
    color: '#64748b',
    desc: '레이더 진단 사이트 공통 템플릿',
  },
  {
    id: 'make-it-mine-35',
    name: '공직자 소명 진단',
    sub: 'Make It Mine 35',
    category: 'diagnosis',
    status: 'running',
    adsense: 'none',
    gsc: false,
    seoText: false,
    domain: 'make-it-mine-35.vercel.app',
    github: 'CHOBH1024/make-it-mine-35',
    icon: 'fa-landmark',
    color: '#a78bfa',
    desc: '공직자 소명 아키타입 진단',
  },

  // ── 가정연합·사역 ────────────────────────────────────────
  {
    id: 'gajeongworld',
    name: '그루터기',
    sub: '신앙 성장 커뮤니티',
    category: 'ministry',
    status: 'running',
    adsense: 'none',
    gsc: false,
    seoText: false,
    domain: 'gajeongworld.vercel.app',
    github: 'CHOBH1024/gajeongworld',
    icon: 'fa-seedling',
    color: '#34d399',
    desc: '진단 → 로드맵 → 이음 → 숲 → 상담 플랫폼',
  },
  {
    id: 'mijeonshi',
    name: '미전시',
    sub: '미라클 전도 시뮬레이션',
    category: 'ministry',
    status: 'running',
    adsense: 'none',
    gsc: false,
    seoText: false,
    domain: 'mijeonshi.vercel.app',
    github: 'CHOBH1024/mijeonshi',
    icon: 'fa-chess-knight',
    color: '#be185d',
    desc: '전도자 클래스·60일 캘린더 비주얼노벨',
  },
  {
    id: 'ffwpu-youth-app',
    name: '통밋업',
    sub: '청년 식구 커뮤니티',
    category: 'ministry',
    status: 'running',
    adsense: 'none',
    gsc: false,
    seoText: false,
    domain: 'ffwpu-youth-app.vercel.app',
    github: 'CHOBH1024/ffwpu-youth-app',
    icon: 'fa-users',
    color: '#f59e0b',
    desc: '가정연합 청년 커뮤니티 프로토타입',
  },

  // ── 콘텐츠·도구 ──────────────────────────────────────────
  {
    id: 'jeongbu',
    name: '별의별 계산기',
    sub: '재무·생활 계산기',
    category: 'tools',
    status: 'running',
    adsense: 'pending',
    gsc: true,
    seoText: true,
    domain: 'jeongbu.vercel.app',
    github: 'CHOBH1024/jeongbu',
    icon: 'fa-calculator',
    color: '#84cc16',
    desc: '스마트 재무·생활 계산기 모음',
  },
  {
    id: 'jikjang',
    name: '직장인 가이드',
    sub: '직장 생활 정보',
    category: 'content',
    status: 'running',
    adsense: 'approved',
    gsc: true,
    seoText: false,
    domain: 'jikjang.vercel.app',
    github: 'CHOBH1024/jikjang',
    icon: 'fa-briefcase',
    color: '#fb7185',
    desc: '직장인 실무·커리어 정보 (AdSense 승인)',
  },
  {
    id: 'hyper-automation-tower',
    name: '테크팁KR',
    sub: 'AI 기술 레퍼런스',
    category: 'content',
    status: 'running',
    adsense: 'pending',
    gsc: true,
    seoText: true,
    domain: 'hyper-automation-tower.vercel.app',
    github: 'CHOBH1024/hyper-automation-tower',
    icon: 'fa-laptop-code',
    color: '#f97316',
    desc: 'AI·자동화 기술 레퍼런스 블로그',
  },
  {
    id: 'serverguchuk',
    name: '서버구축1024',
    sub: 'IT 아키텍처 저널',
    category: 'content',
    status: 'running',
    adsense: 'pending',
    gsc: true,
    seoText: true,
    domain: 'serverguchuk1024.vercel.app',
    github: 'CHOBH1024/serverguchuk1024',
    icon: 'fa-server',
    color: '#22d3ee',
    desc: '수익형 IT 블로그·서버 구축 가이드',
  },
  {
    id: 'juganbogo3',
    name: '주간보고 v3',
    sub: '주간보고서',
    category: 'tools',
    status: 'running',
    adsense: 'none',
    gsc: false,
    seoText: false,
    domain: 'juganbogo3.vercel.app',
    github: 'CHOBH1024/juganbogo3',
    icon: 'fa-file-lines',
    color: '#94a3b8',
    desc: '주간보고서 시스템 v3',
  },
  {
    id: 'dowajoyo',
    name: '도와줘요',
    sub: '지원 도구',
    category: 'tools',
    status: 'running',
    adsense: 'none',
    gsc: false,
    seoText: false,
    domain: 'dowajoyo.vercel.app',
    github: 'CHOBH1024/dowajoyo',
    icon: 'fa-hand-holding-heart',
    color: '#38bdf8',
    desc: '지원·헬프 관련 도구 사이트',
  },

  // ── 관제 ─────────────────────────────────────────────────
  {
    id: 'control-tower',
    name: 'Anti 관제탑',
    sub: '통합 대시보드',
    category: 'ops',
    status: 'running',
    adsense: 'none',
    gsc: false,
    seoText: false,
    domain: 'control-tower.vercel.app',
    github: 'CHOBH1024/control-tower',
    icon: 'fa-tower-broadcast',
    color: '#38bdf8',
    desc: '전체 사이트 헬스·AdSense·알림 관제',
  },
];

module.exports = { SITES };
